// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // ts-node, not tsx: tsx isn't a dependency of this project, so the
    // generated default made `prisma db seed` fail on a clean install.
    // Same runner as the `prisma:seed` npm script.
    seed: "npx ts-node prisma/seed.ts",
  },
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
